### PR TITLE
[🐛 FIX] warnings

### PR DESCRIPTION
**Pull request by andrei-pavel**
* signed/unsigned comparisons
* superfluous casts
* cast unused parameters to void
* implicit fallthrough
* no newline at end of file

### CODE REVIEW

**Comment by orhun** [comment]
Using fallthrough is necessary for `-l` and `-r` arguments to work as expected. I'm not saying it's a good practice but it's running normally with fallthough right now. 
Other changes seem OK but I can't merge this pull request until I refactor `parseArgs` function.

**Comment by andrei-pavel** [comment]
This is amazing. gcc recognizes the `// fall through` comment and if spelled exactly like that, it silences the comment. clang doesn't complain to start with.

Sorry, I saw `-l` said `list` and `-r` said `don't list` and I thought they step on each other's toes.

**Comment by andrei-pavel** [comment]
Thank you for creating this! :clinking_glasses:  :1st_place_medal:

**Comment by orhun** [comment]
Thanks for your contribution! :octocat:

**Pull request merged**
